### ISSUE TITLE
Usefull example to integrate in the asio grpc repository

### ISSUE THREAD

**Issue by rogerworld** [Tradias/example-vcpkg-grpc#1]
Hello Tradias,

I spotted an issue with the code, when a client disconnects, the program remains in a waiting state. And after reconnection the client doesn't receive any data.
BTW, The example of long-lived streaming is usefull.
It can be integrated into the agrpc repository.
It's gonna be helpful for many people.
Thanks for your time.

**Comment by Tradias** [comment]
Hi,

since you weren't very precise in the exact behavior of the producer, I made it the simplest possible. It starts producing data on the very first connection after program start and will continue to produce for 8s (see `produce_data` function). Clients that reconnect during that time will also get the remaining responses. Obviously this might need to be adjusted to your use case, which is why I left [the comment](https://github.com/Tradias/example-vcpkg-grpc/blob/dcd17b6abc641d8652af9f1851d7d53cd62a0f6f/src/main.cpp#LL114C37-L116C37). You could have one producer per client, created when a client connects; producers could be shared between clients; etc. I do not know your use case.

I don't think this example needs to be in asio-grpc. There are essentially only two lines of code from asio-grpc, the rest is asio. Besides there is already a [similar example](https://github.com/Tradias/asio-grpc/blob/master/example/streaming-server.cpp#L113) anyways.
